### ISSUE TITLE
Panic formatting conditional expression with inner binary expression with zero fill right shift

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#183]
For some reason this panics:

```ts
test ? -(value >>> 1) : value >>> 1
```

```
thread 'test_specs' panicked at 'called `Option::unwrap()` on a `None` value', src\parser.rs:1299:30
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<test::helpers::sink::Sink>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\io\mod.rs:1426
   5: std::io::impls::{{impl}}::write_fmt<Write>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\impls.rs:156
   6: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   9: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:221
  10: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  11: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  12: core::panicking::panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:85
  13: core::panicking::panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:52
  14: core::option::Option<swc_ecma_parser::token::TokenAndSpan*>::unwrap<swc_ecma_parser::token::TokenAndSpan*>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\macros\mod.rs:10
  15: dprint_plugin_typescript::parser::parse_binary_expr::inner_parse
             at .\src\parser.rs:1299
  16: dprint_plugin_typescript::parser::parse_binary_expr
             at .\src\parser.rs:1294
  17: dprint_plugin_typescript::parser::parse_node_with_inner_parse::parse_node_inner
             at .\src\parser.rs:126
  18: dprint_plugin_typescript::parser::parse_node_with_inner_parse<closure-3>
             at .\src\parser.rs:77
  19: dprint_plugin_typescript::parser::parse_conditional_expr
             at .\src\parser.rs:1767
  20: dprint_plugin_typescript::parser::parse_node_with_inner_parse::parse_node_inner
             at .\src\parser.rs:129
```

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/751
