### ISSUE TITLE
Panic related to plugin pool

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#356]
https://github.com/denoland/deno/pull/10509/checks?check_run_id=2511321135

```
dprint
Error: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/dprint/src/plugins/pool.rs:115:82
stack backtrace:
   0:     0x557e05c9f990 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x557e05c9f990 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x557e05c9f990 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x557e05c9f990 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x557e05cc7dac - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x557e05c97d02 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x557e05ca213d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x557e05ca213d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x557e05ca213d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x557e05ca1de8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x557e05ca2821 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x557e05ca23c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x557e05c9fdfc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x557e05ca2389 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x557e05cc59d1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x557e05cc591d - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x557e05669d2e - dprint::plugins::pool::PluginPools<TEnvironment>::release_instance_for_plugin::h0167d9406dfecf36
  17:     0x557e05640976 - dprint::plugins::implementations::common::format_with_plugin_pool::h67e2fcbc474b626a
  18:     0x557e05606a94 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he498374834d99e0e
  19:     0x557e0568a814 - <Func as wasmer::externals::function::inner::HostFunction<(),Rets,wasmer::externals::function::inner::WithEnv,Env>>::function_body_ptr::func_wrapper::h344d324bb77c97cd
  20:     0x7ff09ca68b9d - <unknown>
  21:     0x7ff09ca81b70 - <unknown>
  22:     0x7ff09ca8dff4 - <unknown>
  23:     0x7ff09ca8054d - <unknown>
  24:     0x7ff09ca57317 - <unknown>
  25:     0x7ff09ca7c5fc - <unknown>
  26:     0x7ff09ca6c1ff - <unknown>
  27:     0x7ff09cd75246 - <unknown>
A panic occurred. You may want to run in verbose mode (--verbose) to help figure out where it failed then report this as a bug.
error: Uncaught (in promise) Error: dprint failed
    throw new Error("dprint failed");
          ^
    at dprint (file:///home/runner/work/deno/deno/tools/format.js:14:11)
    at async main (file:///home/runner/work/deno/deno/tools/format.js:40:3)
    at async file:///home/runner/work/deno/deno/tools/format.js:64:1
```

**Comment by lucacasonato** [comment]
Just happened again on the rerun - https://github.com/denoland/deno/pull/10509/checks?check_run_id=2511354670
