### ISSUE TITLE
dprint attempts to format files in .git

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint#833]
Version: 0.45.0

```console
$ mkdir wat
$ cd wat
$ git init
$ dprint init
$ git commit -am "init"
$ git switch -c test.d.ts
$ dprint fmt
dprint fmt
Error formatting /home/jabaile/wat/.git/refs/heads/test.d.ts. Message: Identifier cannot follow number at file:///home/jabaile/wat/.git/refs/heads/test.d.ts:1:3

  20ba1a6a14151f3a90d7638555294cfad31f451f
    ~
Error formatting /home/jabaile/wat/.git/logs/refs/heads/test.d.ts. Message: Identifier cannot follow number at file:///home/jabaile/wat/.git/logs/refs/heads/test.d.ts:1:44

  0000000000000000000000000000000000000000 20ba1a6a14151f3a90d7638555294cfad31f451...
                                             ~
Had 2 errors formatting.
```

This just surprised someone on my team; it doesn't seem like formatting in `.git` will ever be a good idea, even worse than `node_modules`; can this directory be ignored by default?

**Comment by jakebailey** [comment]
ref: https://github.com/microsoft/TypeScript/pull/57935#pullrequestreview-1958543554
