### ISSUE TITLE
Tests failing on Alpine

### ISSUE THREAD

**Issue by kaathewisegit** [dprint/dprint#864]
Good day!

I was packaging `dprint` for Alpine's aports, but a quite few tests are failing on main and 0.46.3.  Is this is an issue on my end, or do some tests not work at the moment?

**Comment by dsherret** [comment]
What error are you getting? It works on the ci

**Comment by KAAtheWiseGit** [comment]
https://paste.sr.ht/~kaathewise/eb33e549e2f0809aa1b51bdbcf895321df500007

Most of the failures look plugin-related

**Comment by dsherret** [comment]
Can you paste here instead of linking to another site?

**Comment by KAAtheWiseGit** [comment]
Updated the comment.  The commit is 35c795a7

**Comment by dsherret** [comment]
Thanks. Is there more detail if you run a single failing test?

**Comment by KAAtheWiseGit** [comment]
```
~/fork/dprint> cargo test commands::config::test::config_add -- --nocapture
...
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.18s
     Running unittests src/main.rs (target/debug/deps/dprint-ada9ff8ad2d279ac)

running 1 test
thread 'commands::config::test::config_add' panicked at crates/dprint/src/test_helpers.rs:43:58:
Could not canonicalize /home/kaathewise/fork/dprint/crates/dprint/../../target/debug/test-process-plugin: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test commands::config::test::config_add ... FAILED

failures:

failures:
    commands::config::test::config_add

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 299 filtered out; finished in 0.01s

error: test failed, to rerun pass `-p dprint --bin dprint`
```

Wait, does `dprint` need any testing dependencies?  I haven't thought about it, so I don't have any installed

**Comment by KAAtheWiseGit** [comment]
And I'm also running this on Alpine, which uses musl as its libc, not glibc.  And `/tmp` is a tmpfs, but it doesn't seem like the tests get to the creating files stage

**Comment by dsherret** [comment]
Try running `cargo build` first. The error message should be improved in the future.

**Comment by KAAtheWiseGit** [comment]
Huh.  This makes all tests pass, but the test command still fails:

```sh
~/fork/dprint> cargo test
...
warning: `dprint` (bin "dprint" test) generated 2 warnings
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.18s
     Running unittests src/main.rs (target/debug/deps/dprint-ada9ff8ad2d279ac)

running 300 tests
test arg_parser::test::version_flag ... ok
test arg_parser::test::plugins_with_file_paths_no_dash_at_first ... ok
test arg_parser::test::plugins_with_file_paths_no_dash_after_first ... ok
test arg_parser::test::incremental_arg ... ok
test commands::config::test::should_output_resolved_config_no_plugins ... ok
test commands::config::test::should_initialize ... ok
test commands::config::test::should_initialize_with_specified_config_path ... ok
test commands::config::test::should_use_dprint_config_init_as_alias ... ok
test commands::config::test::should_error_when_config_file_exists_on_initialize ... ok
test commands::formatting::test::should_allow_using_no_config_when_plugins_specified ... ok
test commands::formatting::test::allow_skipping_stable_format ... ok
test commands::config::test::config_update_should_handle_wasm_to_process_plugin ... ok
test commands::formatting::test::incremental_should_error_for_unstable_format_that_errors ... ok
test commands::formatting::test::should_combine_config_excludes_with_cli_excludes ... ok
test commands::config::test::config_update_should_not_upgrade_when_at_latest_plugins ... ok
test commands::formatting::test::should_combine_config_excludes_with_cli_args ... ok
test commands::formatting::test::incremental_should_error_for_unstable_format ... ok
test commands::formatting::test::should_error_format_to_empty ... ok
test commands::formatting::test::should_error_if_process_plugin_has_no_checksum_in_config ... ok
test commands::formatting::test::should_error_if_process_plugin_has_wrong_checksum_in_config ... ok
test commands::formatting::test::should_error_if_wasm_plugin_has_wrong_checksum_in_config ... ok
test commands::formatting::test::should_error_on_wasm_plugin_config_diagnostic ... ok
test commands::formatting::test::should_error_when_config_file_does_not_exist ... ok
test commands::formatting::test::should_error_once_on_config_diagnostic_many_files ... ok
test commands::formatting::test::should_error_when_no_plugins_specified ... ok
test commands::formatting::test::should_error_when_no_files_match_glob ... ok
test commands::formatting::test::should_exclude_a_specified_dot_slash_path ... ok
error: test failed, to rerun pass `-p dprint --bin dprint`

Caused by:
  process didn't exit successfully: `/home/kaathewise/fork/dprint/target/debug/deps/dprint-ada9ff8ad2d279ac` (signal: 6, SIGABRT: process abort signal)
```

**Comment by KAAtheWiseGit** [comment]
And it's also not deterministic.  Sometimes 20 tests are completed before this error, sometimes 40 or 60.  But all of the finished tests succeed

**Comment by dsherret** [comment]
Probably one of the tests is segfaulting on your platform.

**Comment by KAAtheWiseGit** [comment]
I got some help, and we managed to locate the segfault:

```gdb
#0  __restore_sigs (set=set@entry=0x7ffff3f28f70) at ./arch/x86_64/syscall_arch.h:40
#1  0x00007ffff7fa9845 in raise (sig=sig@entry=6) at src/signal/raise.c:11
#2  0x00007ffff7f78c21 in abort () at src/exit/abort.c:11
#3  0x00007ffff7f360e1 in ?? () from /usr/lib/libgcc_s.so.1
#4  0x00007ffff7f4e67a in __deregister_frame () from /usr/lib/libgcc_s.so.1
#5  0x00005555575e85ef in wasmer_compiler::engine::unwind::systemv::{impl#1}::drop (self=0x7ffff3238060) at src/engine/unwind/systemv.rs:119
#6  0x00005555575cde17 in core::ptr::drop_in_place<wasmer_compiler::engine::unwind::systemv::UnwindRegistry> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#7  0x00005555575cd91f in core::ptr::drop_in_place<wasmer_compiler::engine::code_memory::CodeMemory> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#8  0x00005555575cdec1 in core::ptr::drop_in_place<[wasmer_compiler::engine::code_memory::CodeMemory]> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#9  0x000055555759e703 in alloc::vec::{impl#25}::drop<wasmer_compiler::engine::code_memory::CodeMemory, alloc::alloc::Global> (self=0x7ffff06c3028)
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:3283
#10 0x00005555575ce4d7 in core::ptr::drop_in_place<alloc::vec::Vec<wasmer_compiler::engine::code_memory::CodeMemory, alloc::alloc::Global>> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#11 0x00005555575cd51b in core::ptr::drop_in_place<wasmer_compiler::engine::inner::EngineInner> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#12 0x00005555575ce5eb in core::ptr::drop_in_place<core::cell::UnsafeCell<wasmer_compiler::engine::inner::EngineInner>> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#13 0x00005555575ce67f in core::ptr::drop_in_place<std::sync::mutex::Mutex<wasmer_compiler::engine::inner::EngineInner>> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#14 0x00005555575de71f in alloc::sync::Arc<std::sync::mutex::Mutex<wasmer_compiler::engine::inner::EngineInner>, alloc::alloc::Global>::drop_slow<std::sync::mutex::Mutex<wasmer_compiler::engine::inner::EngineInner>, alloc::alloc::Global> (self=0x7ffff3f296d0) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/sync.rs:1812
#15 0x00005555575ded92 in alloc::sync::{impl#34}::drop<std::sync::mutex::Mutex<wasmer_compiler::engine::inner::EngineInner>, alloc::alloc::Global> (self=0x7ffff3f296d0)
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/sync.rs:2470
#16 0x00005555575cc26b in core::ptr::drop_in_place<alloc::sync::Arc<std::sync::mutex::Mutex<wasmer_compiler::engine::inner::EngineInner>, alloc::alloc::Global>> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#17 0x0000555556ab937b in core::ptr::drop_in_place<wasmer_compiler::engine::inner::Engine> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#18 0x0000555556ab8c4b in core::ptr::drop_in_place<wasmer::engine::Engine> () at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#19 0x000055555637d6f4 in core::ptr::drop_in_place<dprint::plugins::implementations::wasm::load_instance::WasmModule> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514
#20 0x0000555555f7b362 in dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure#1}<dprint::environment::test_environment::TestEnvironment> () at crates/dprint/src/plugins/implementations/wasm/plugin.rs:314
#21 0x0000555556442663 in dprint_core::async_runtime::spawn_blocking::{closure#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()> () at crates/core/src/async_runtime.rs:69
#22 0x0000555555f80734 in tokio::runtime::blocking::task::{impl#2}::poll<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>, dprint_core::async_runtime::MaskResultAsSend<()>> (self=..., _cx=0x7ffff3f29a60) at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42
#23 0x0000555555aa6178 in tokio::runtime::task::core::{impl#6}::poll::{closure#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (ptr=0x7ffff298f4a8)
    at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328
#24 0x0000555555a9f921 in tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime:--Type <RET> for more, q to quit, c to continue without paging--c
:spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>>, core::task::poll::Poll<dprint_core::async_runtime::MaskResultAsSend<()>>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>> (self=0x7ffff298f4a8, f=...)
    at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16
#25 tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (self=0x7ffff298f4a0, cx=...) at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317
#26 0x0000555555c71c7a in tokio::runtime::task::harness::poll_future::{closure#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> ()
    at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485
#27 0x00005555557c9620 in core::panic::unwind_safe::{impl#23}::call_once<core::task::poll::Poll<dprint_core::async_runtime::MaskResultAsSend<()>>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>> (self=...) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272
#28 0x0000555555b077d9 in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<dprint_core::async_runtime::MaskResultAsSend<()>>> (data=0x7ffff3f29b98) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559
#29 0x0000555555b382ab in __rust_try ()
#30 0x0000555555af9996 in std::panicking::try<core::task::poll::Poll<dprint_core::async_runtime::MaskResultAsSend<()>>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>>> (f=...) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523
#31 0x0000555555f0d18d in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<dprint_core::async_runtime::MaskResultAsSend<()>>> (f=...) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149
#32 0x0000555555c5d42f in tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (core=0x7ffff298f4a0, cx=...)
    at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473
#33 0x0000555555c7a217 in tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>::poll_inner<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (self=0x7ffff3f29df0)
    at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208
#34 0x0000555555ca1e73 in tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (self=...) at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153
#35 0x000055555618cb0b in tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<dprint_core::async_runtime::spawn_blocking::{closure_env#0}<dprint::plugins::implementations::wasm::plugin::{impl#2}::create_instance::{async_fn#0}::{closure_env#1}<dprint::environment::test_environment::TestEnvironment>, ()>>, tokio::runtime::blocking::schedule::BlockingSchedule> (ptr=...) at /home/kaathewise/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271
#36 0x0000555557d3dcd7 in tokio::runtime::task::raw::RawTask::poll (self=...) at src/runtime/task/raw.rs:201
#37 0x0000555557d71127 in tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>::run<tokio::runtime::blocking::schedule::BlockingSchedule>
    (self=...) at src/runtime/task/mod.rs:464
#38 0x0000555557d571d7 in tokio::runtime::blocking::pool::Task::run (self=...) at src/runtime/blocking/pool.rs:159
#39 0x0000555557d5b953 in tokio::runtime::blocking::pool::Inner::run (self=0x7ffff606f460, worker_thread_id=0) at src/runtime/blocking/pool.rs:513
#40 0x0000555557d5b654 in tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure#0} () at src/runtime/blocking/pool.rs:471
#41 0x0000555557d63266 in std::sys_common::backtrace::__rust_begin_short_backtrace<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()> (
    f=<error reading variable: Cannot access memory at address 0x2>) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155
#42 0x0000555557d73e82 in std::thread::{impl#0}::spawn_unchecked_::{closure#2}::{closure#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:542
#43 0x0000555557d68542 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#2}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>> (self=...) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272
#44 0x0000555557d42943 in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#2}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()> (data=0x7ffff3f2a2b0)
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559
#45 0x0000555557d453fb in __rust_try ()
#46 0x0000555557d420b1 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#2}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>> (f=...) at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523
#47 0x0000555557d73abb in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#2}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()> (f=<error reading variable: Cannot access memory at address 0x0>)
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149
#48 std::thread::{impl#0}::spawn_unchecked_::{closure#2}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()> ()
    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:541
#49 0x0000555557d741bf in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#2}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>, ()> () at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250
#50 0x0000555557ddd2fb in std::sys::pal::unix::thread::Thread::new::thread_start ()
#51 0x00007ffff7fb8349 in start (p=0x7ffff3f2a548) at src/thread/pthread_create.c:207
#52 0x00007ffff7fba95f in __clone () at src/thread/x86_64/clone.s:22
```

It looks like null pointer dereferencing (`#47`) in a clone (?)

**Comment by dsherret** [comment]
Maybe upgrading wasmer will fix it: https://github.com/dprint/dprint/pull/865

**Comment by KAAtheWiseGit** [comment]
@dsherret I checked with wasmer 4.3.2, but the issue persists.  I think I'll stop the port for now and come back in a few months, after the dependencies move forward

**Comment by KAAtheWiseGit** [comment]
Thanks for the help nonetheless!

**Comment by qaqland** [comment]
I can confirm that all the tests have passed.
