### ISSUE TITLE
Cannot find module @dprint/linux-x64-glibc/package.json on install

### ISSUE THREAD

**Issue by otakustay** [dprint/dprint#942]
I have `dprint@^0.47.5` in my `devDependencies`, this is a full error message on my GitHub Action:

```text
npm error code 1
npm error path /home/runner/work/async-iterator/async-iterator/node_modules/dprint
npm error command failed
npm error command sh -c node ./install.js
npm error node:internal/modules/cjs/loader:1228
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module '@dprint/linux-x64-glibc/package.json'
npm error Require stack:
npm error - /home/runner/work/async-iterator/async-iterator/node_modules/dprint/install_api.js
npm error - /home/runner/work/async-iterator/async-iterator/node_modules/dprint/install.js
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:122[5](https://github.com/otakustay/async-iterator/actions/runs/12063684193/job/33639259482?pr=11#step:4:6):15)
npm error     at Function.resolve (node:internal/modules/helpers:190:19)
npm error     at Object.runInstall (/home/runner/work/async-iterator/async-iterator/node_modules/dprint/install_api.js:23:52)
npm error     at Object.<anonymous> (/home/runner/work/async-iterator/async-iterator/node_modules/dprint/install.js:4:2[6](https://github.com/otakustay/async-iterator/actions/runs/12063684193/job/33639259482?pr=11#step:4:7))
npm error     at Module._compile (node:internal/modules/cjs/loader:1469:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1288:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1104:12)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:1[7](https://github.com/otakustay/async-iterator/actions/runs/12063684193/job/33639259482?pr=11#step:4:8)3:12)
npm error     at node:internal/main/run_main_module:2[8](https://github.com/otakustay/async-iterator/actions/runs/12063684193/job/33639259482?pr=11#step:4:9):49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: [
npm error     '/home/runner/work/async-iterator/async-iterator/node_modules/dprint/install_api.js',
npm error     '/home/runner/work/async-iterator/async-iterator/node_modules/dprint/install.js'
npm error   ]
npm error }
npm error
npm error Node.js v20.18.1
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-[11](https://github.com/otakustay/async-iterator/actions/runs/12063684193/job/33639259482?pr=11#step:4:12)-28T06_28_52_771Z-debug-0.log
```

**Comment by otakustay** [comment]
Cuased by https://github.com/npm/cli/issues/4828
